export const SHIPPING_METHODS = [
  // らくらくメルカリ便（匿名）
  { name: 'ネコポス', cost: 210, anonymous: true, group: 'らくらくメルカリ便',
    maxSize: { w: 31.2, h: 22.8, d: 3, sum: null }, maxWeight: 1000 },
  { name: '宅急便コンパクト', cost: 450, anonymous: true, group: 'らくらくメルカリ便',
    maxSize: { w: 25, h: 20, d: 5, sum: null }, maxWeight: null },
  { name: '宅急便 60サイズ', cost: 750, anonymous: true, group: 'らくらくメルカリ便',
    maxSize: { w: null, h: null, d: null, sum: 60 }, maxWeight: 2000 },
  { name: '宅急便 80サイズ', cost: 850, anonymous: true, group: 'らくらくメルカリ便',
    maxSize: { w: null, h: null, d: null, sum: 80 }, maxWeight: 5000 },
  { name: '宅急便 100サイズ', cost: 1050, anonymous: true, group: 'らくらくメルカリ便',
    maxSize: { w: null, h: null, d: null, sum: 100 }, maxWeight: 10000 },
  { name: '宅急便 120サイズ', cost: 1200, anonymous: true, group: 'らくらくメルカリ便',
    maxSize: { w: null, h: null, d: null, sum: 120 }, maxWeight: 15000 },
  { name: '宅急便 140サイズ', cost: 1450, anonymous: true, group: 'らくらくメルカリ便',
    maxSize: { w: null, h: null, d: null, sum: 140 }, maxWeight: 20000 },
  { name: '宅急便 160サイズ', cost: 1700, anonymous: true, group: 'らくらくメルカリ便',
    maxSize: { w: null, h: null, d: null, sum: 160 }, maxWeight: 25000 },
  // ゆうゆうメルカリ便（匿名）
  { name: 'ゆうパケット', cost: 230, anonymous: true, group: 'ゆうゆうメルカリ便',
    maxSize: { w: 34, h: 25, d: 3, sum: null }, maxWeight: 1000 },
  { name: 'ゆうパケットポスト', cost: 215, anonymous: true, group: 'ゆうゆうメルカリ便',
    maxSize: { w: 32.7, h: 22.8, d: 4, sum: null }, maxWeight: 2000,
    note: '※厚さは4cmまでで判定していますがポストにより異なります' },
  { name: 'ゆうパケットポストミニ', cost: 160, anonymous: true, group: 'ゆうゆうメルカリ便',
    maxSize: { w: 21.6, h: 17, d: 4, sum: null }, maxWeight: 2000,
    note: '※厚さは4cmまでで判定していますがポストにより異なります' },
  { name: 'ゆうパケットプラス', cost: 455, anonymous: true, group: 'ゆうゆうメルカリ便',
    maxSize: { w: 24, h: 17, d: 7, sum: null }, maxWeight: 2000 },
  { name: 'ゆうパック 60サイズ', cost: 770, anonymous: true, group: 'ゆうゆうメルカリ便',
    maxSize: { w: null, h: null, d: null, sum: 60 }, maxWeight: 25000 },
  { name: 'ゆうパック 80サイズ', cost: 870, anonymous: true, group: 'ゆうゆうメルカリ便',
    maxSize: { w: null, h: null, d: null, sum: 80 }, maxWeight: 25000 },
  { name: 'ゆうパック 100サイズ', cost: 1070, anonymous: true, group: 'ゆうゆうメルカリ便',
    maxSize: { w: null, h: null, d: null, sum: 100 }, maxWeight: 25000 },
  // 普通郵便（非匿名）
  { name: '定形郵便 25g', cost: 84, anonymous: false, group: '普通郵便',
    maxSize: { w: 23.5, h: 12, d: 1, sum: null }, maxWeight: 25 },
  { name: '定形郵便 50g', cost: 94, anonymous: false, group: '普通郵便',
    maxSize: { w: 23.5, h: 12, d: 1, sum: null }, maxWeight: 50 },
  { name: '定形外(規格内) 50g', cost: 120, anonymous: false, group: '普通郵便',
    maxSize: { w: 34, h: 25, d: 3, sum: null }, maxWeight: 50 },
  { name: '定形外(規格内) 100g', cost: 140, anonymous: false, group: '普通郵便',
    maxSize: { w: 34, h: 25, d: 3, sum: null }, maxWeight: 100 },
  { name: '定形外(規格内) 150g', cost: 210, anonymous: false, group: '普通郵便',
    maxSize: { w: 34, h: 25, d: 3, sum: null }, maxWeight: 150 },
  { name: '定形外(規格内) 250g', cost: 250, anonymous: false, group: '普通郵便',
    maxSize: { w: 34, h: 25, d: 3, sum: null }, maxWeight: 250 },
  { name: '定形外(規格内) 500g', cost: 390, anonymous: false, group: '普通郵便',
    maxSize: { w: 34, h: 25, d: 3, sum: null }, maxWeight: 500 },
  { name: '定形外(規格内) 1kg', cost: 580, anonymous: false, group: '普通郵便',
    maxSize: { w: 34, h: 25, d: 3, sum: null }, maxWeight: 1000 },
  { name: '定形外(規格外) 50g', cost: 200, anonymous: false, group: '普通郵便',
    maxSize: { w: 60, h: null, d: null, sum: 90 }, maxWeight: 50 },
  { name: '定形外(規格外) 100g', cost: 220, anonymous: false, group: '普通郵便',
    maxSize: { w: 60, h: null, d: null, sum: 90 }, maxWeight: 100 },
  { name: '定形外(規格外) 150g', cost: 300, anonymous: false, group: '普通郵便',
    maxSize: { w: 60, h: null, d: null, sum: 90 }, maxWeight: 150 },
  { name: '定形外(規格外) 250g', cost: 350, anonymous: false, group: '普通郵便',
    maxSize: { w: 60, h: null, d: null, sum: 90 }, maxWeight: 250 },
  { name: '定形外(規格外) 500g', cost: 510, anonymous: false, group: '普通郵便',
    maxSize: { w: 60, h: null, d: null, sum: 90 }, maxWeight: 500 },
  { name: '定形外(規格外) 1kg', cost: 710, anonymous: false, group: '普通郵便',
    maxSize: { w: 60, h: null, d: null, sum: 90 }, maxWeight: 1000 },
  { name: '定形外(規格外) 2kg', cost: 1040, anonymous: false, group: '普通郵便',
    maxSize: { w: 60, h: null, d: null, sum: 90 }, maxWeight: 2000 },
  { name: '定形外(規格外) 4kg', cost: 1350, anonymous: false, group: '普通郵便',
    maxSize: { w: 60, h: null, d: null, sum: 90 }, maxWeight: 4000 },
  // その他（非匿名）
  { name: 'クリックポスト', cost: 185, anonymous: false, group: 'その他',
    maxSize: { w: 34, h: 25, d: 3, sum: null }, maxWeight: 1000 },
  { name: 'レターパックライト', cost: 370, anonymous: false, group: 'その他',
    maxSize: { w: 34, h: 24.8, d: 3, sum: null }, maxWeight: 4000 },
  { name: 'レターパックプラス', cost: 520, anonymous: false, group: 'その他',
    maxSize: { w: 34, h: 24.8, d: null, sum: null }, maxWeight: 4000 },
];

export const KEYWORDS = {
  'レディース': ['新品', '未使用', '美品', 'タグ付き', '送料無料', '即購入OK', '限定', 'セール', 'ワンピース', 'トップス', 'スカート', 'パンツ'],
  'メンズ': ['新品', '未使用', '美品', 'タグ付き', '送料無料', '即購入OK', '限定', 'Tシャツ', 'ジャケット', 'パンツ', 'スニーカー'],
  '家電・スマホ': ['新品', '未使用', '美品', '動作確認済', '付属品完備', '送料無料', '即購入OK', 'iPhone', 'Android', 'イヤホン'],
  '本・雑誌': ['新品', '未使用', '美品', '初版', '帯付き', '送料無料', '即購入OK', 'セット', 'まとめ売り', '全巻'],
  'コスメ・美容': ['新品', '未使用', '未開封', '残量8割', '送料無料', '即購入OK', '限定', 'デパコス', 'プチプラ'],
  'ゲーム・おもちゃ': ['新品', '未使用', '美品', '動作確認済', '送料無料', '即購入OK', '限定', 'レア', 'セット', 'まとめ']
};
